version: '3.8'

services:
  app:
    container_name: socialnetwork
    build: .
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - mysql
    volumes:
      - ./:/usr/src/app
  mysql:
    container_name: socialnetwork_mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=12346
      - MYSQL_DATABASE=network
    ports:
      - "3308:3306"
    volumes:
      - socialnetwork-mysql-volume:/var/lib/mysql
volumes:
  socialnetwork-mysql-volume:
